// <auto-generated />
using System;
using Identity.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20260320222533_FirtsMigratiions")]
    partial class FirtsMigratiions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.Identity.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Algorithm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ALGORITMO");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_EXPIRACION");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMO_USO");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HASH_SECRETO");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CREDENCIAL_USUARIO_ID");

                    b.ToTable("CREDENCIAL", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMO_INICIO_SESION");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_VINCULACION");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("CORREO_PROVEEDOR");

                    b.Property<bool>("ProviderEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("CORREO_PROVEEDOR_VERIFICADO");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SUJETO_PROVEEDOR");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_PROVEEDOR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_IDENTIDAD_EXTERNA_USUARIO_ID");

                    b.HasIndex("ProviderType", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("IX_IDENTIDAD_EXTERNA_TIPO_PROVEEDOR_SUJETO_PROVEEDOR");

                    b.ToTable("IDENTIDAD_EXTERNA", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_EXPIRACION");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_EMISION");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REEMPLAZADO_POR_TOKEN_ID");

                    b.Property<DateTime?>("ReuseDetectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_REUSO_DETECTADO");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_REVOCACION");

                    b.Property<Guid?>("RotatedFromTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TOKEN_ROTADO_DESDE_ID");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SESION_ID");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TENANT_ID");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HASH_TOKEN");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_TOKEN_REFRESH_FECHA_EXPIRACION");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("RotatedFromTokenId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_TOKEN_REFRESH_SESION_ID");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_TOKEN_REFRESH_HASH_TOKEN");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TOKEN_REFRESH_USUARIO_ID");

                    b.ToTable("TOKEN_REFRESH", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("METODO_AUTENTICACION");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOMBRE_DISPOSITIVO");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_EXPIRACION");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("DIRECCION_IP");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMA_ACTIVIDAD");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_REVOCACION");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_INICIO");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TENANT_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("USER_AGENT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_SESION_FECHA_EXPIRACION");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SESION_ESTADO");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SESION_TENANT_ID");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SESION_USUARIO_ID");

                    b.ToTable("SESION", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_VINCULACION");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODIGO_ROL");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TENANT_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_MEMBRESIA_TENANT_TENANT_ID");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MEMBRESIA_TENANT_USUARIO_ID");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_MEMBRESIA_TENANT_USUARIO_ID_TENANT_ID");

                    b.ToTable("MEMBRESIA_TENANT", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("URL_AVATAR");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOMBRE_MOSTRAR");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("CORREO_VERIFICADO");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("ES_ADMINISTRADOR_PLATAFORMA");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMO_INICIO_SESION");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("CORREO_PRINCIPAL");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOMBRE_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIO_CORREO_PRINCIPAL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIO_NOMBRE_USUARIO")
                        .HasFilter("[NOMBRE_USUARIO] IS NOT NULL");

                    b.ToTable("USUARIO", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ELIMINACION");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_EXPIRACION");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ES_ELIMINADO");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HASH_TOKEN");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ACTUALIZACION")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_USO");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_TOKEN_VERIFICACION_FECHA_EXPIRACION");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_TOKEN_VERIFICACION_HASH_TOKEN");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TOKEN_VERIFICACION_USUARIO_ID");

                    b.ToTable("TOKEN_VERIFICACION", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.Credential", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Identity.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CREDENCIAL_USUARIO");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Identity.User", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IDENTIDAD_EXTERNA_USUARIO");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Identity.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TOKEN_REFRESH_REEMPLAZADO_POR");

                    b.HasOne("Identity.Domain.Entities.Identity.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("RotatedFromTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TOKEN_REFRESH_ROTADO_DESDE");

                    b.HasOne("Identity.Domain.Entities.Identity.Session", "Session")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TOKEN_REFRESH_SESION");

                    b.HasOne("Identity.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TOKEN_REFRESH_USUARIO");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.Session", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Identity.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SESION_USUARIO");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.TenantMembership", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Identity.User", "User")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEMBRESIA_TENANT_USUARIO");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.VerificationToken", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Identity.User", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TOKEN_VERIFICACION_USUARIO");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.Session", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("Sessions");

                    b.Navigation("TenantMemberships");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
